feat: update hash
Signed-off-by: Carsten Munk <carsten@zippie.com>

diff --git a/packages/vcr-kernels/Dockerfile b/packages/vcr-kernels/Dockerfile
--- a/packages/vcr-kernels/Dockerfile
+++ b/packages/vcr-kernels/Dockerfile
@@ -90,7 +90,7 @@ RUN SOURCE_DATE_EPOCH=0 make FW_PAYLOAD=y FW_OPTIONS=0x01 PLATFORM=cartesi CROSS
 
 RUN sha256sum /work/opensbi/build/platform/cartesi/firmware/fw_payload.bin
 # Verify OpenSBI firmware hash
-RUN echo "b6c975d1c227ba1ef1075a68e5b52f9dff9c0d3010d5be3c1e4023ef0521975e  /work/opensbi/build/platform/cartesi/firmware/fw_payload.bin" | sha256sum -c || (echo "❌ OpenSBI firmware hash verification failed" && exit 1)
+RUN echo "e1ff24dc23c7ff99d42939a851a6a3ef4f8957015942079893b520f12af23377  /work/opensbi/build/platform/cartesi/firmware/fw_payload.bin" | sha256sum -c || (echo "❌ OpenSBI firmware hash verification failed" && exit 1)
 
 FROM --platform=linux/riscv64 ubuntu:24.04 AS perf-builder
 
